[theme]
# Primary accent color for interactive elements.
primaryColor = "#e61919"

# Background color for the main content area.
backgroundColor = "#d9d9d9"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#bfbfbf"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "monospace"
font = "sans serif"